### PR TITLE
Added MenuImageButton

### PR DESCRIPTION
**Pull request by robert4os**
I have used the Android Material Design icon 'menu' https://www.google.com/design/icons/#ic_menu to create icons in the correct sizes. Added support for different densities and created a new class MenuImageButton.

Please ignore a previous pull request (https://github.com/mgwt/mgwt/pull/266) which was from a wrong commit.

### CODE REVIEW

**Comment by waynedyck** [comment]
Thanks for adding this. You'll want to add `.DS_Store` to your `.gitignore` file so it doesn't get included in your pull request like this one did:

`src/main/java/com/googlecode/mgwt/ui/client/widget/image/.DS_Store`

If you want to remove it and then push the change that would be great. Thanks!

**Comment by robert4os** [comment]
Ok, can do :)

One question though, if I add to .gitignore is there a way to exclude .gitignore to be synced with the origin branch?

**Comment by waynedyck** [comment]
Probably best to add that one to your `.gitignore_global` file. Have a look at GitHub's [ignoring files](https://help.github.com/articles/ignoring-files/) article.

**Comment by robert4os** [comment]
Thank you. 

I have created a new pull request, see https://github.com/mgwt/mgwt/pull/275/files

**Comment by waynedyck** [comment]
Thanks, however, you could have simply made another commit to this one. Any changes you make to your branch are automatically picked up in the pull request. I'll try and look at this later today.

**Comment by waynedyck** [comment]
Merged commit 6af556b13b47605ba8f9ff2fc9a3a553e92fc15b

**Pull request closed without merging**
