### PR TITLE
Fix NPE if setSupportCarouselIndicatorTap is called before refresh()

### PR DESCRIPTION
**Pull request by volgin**
Issue #280

### CODE REVIEW

**Comment by volgin** [comment]
When Carousel is created and attached, setSelectedIndex method is called 4 times. I looked at all 4 places that make this call, and found out that two of them are redundant. These calls do not cause any issues, but I don't like redundant code.

I think we can also remove this call from the constructor as ScrollEndEvent is called when carousel is attached, but I left it there for now as it needs more testing/investigating different scenarios.

**Comment by volgin** [comment]
Wayne,

Sorry, it added a new commit to the existing pull request. I have to figure out how to prevent it going forward Please, review my submissions.

In this commit:

1. I added a simple constructor to AlertDialog. I don't think it's necessary to build a new AlertDialog every time there is a new message to be displayed. I prefer to build it once - the first time it's needed, and then show it again and again changing messages as necessary.

2. "Ok" text on a button is hard-coded. Some languages/use cases may require a different text. So I added a method to set this text explicitly in case someone needs it. If not, it will be compiled out, so no harm to the existing use cases.

**Comment by waynedyck** [comment]
What you need to do is create a separate branch for each issue you are working on; that way any commits you make which are unrelated to the original pull request don't go through.

For example if you have a generic "dev" branch you work on and issue a pull request to fix an issue you found, any subsequent commits you make to that branch also come through with the initial pull request.

**Comment by volgin** [comment]
Any chance this bug fix can go into the latest release?

**Comment by waynedyck** [comment]
@paulfrench I'm don't know if you can review this or not. I had originally planned to, however, with my work schedule over the last few months I have not had the opportunity to do anything GWT related.

**Comment by paulfrench** [comment]
@waynedyck yep, leave it with me. I've got to create a beta release of 2.0.1 to keep some others happy. It's all new to me so I'm being careful. I'll merge this pull request if it looks okay before I make a beta release. Cheers

**Comment by volgin** [comment]
Paul,

Thank you!

Let me know if you need any help with this or any other pull requests.

Andrei Volgin

**Comment by waynedyck** [comment]
If there is redundant code in this file it is likely the result of commit 34bbbf2fd742637782cadf41ee821476c510f751 which I did. The original pull request was reviewed by Daniel with the author, however, there were 10 separate commits to this particular file I was attempting to squash down into one. It was a bit of a mess.

**Comment by paulfrench** [comment]
Hello Andrei

I pulled in your master branch as a starting point but like Wayne anticipated there were a few other bugs when you dynamically remove/add the carousel indicator. Anyway I've tested this in showcase and also tested removing/adding the indicator dynamically and also removing/adding tap support dynamically. I've created a pull request which is ready to be merged. It also includes the changes you added to the AlertDialog which I wanted to do as a separate pull request but it has accidentally crept in to this pull request. Since the changes are minor and backwards compatible I will leave it. So if you can check you are happy with....

https://github.com/mgwt/mgwt/pull/288 

...and I will merge.

**Comment by volgin** [comment]
Paul,

I haven't tested it, but upon careful examination it all looks very good.

Andrei

**Pull request merged**
